export type AttractionImage = {
  id?: number;
  attraction_id?: number;
  image_url: string;
  thumbnail_url?: string | null;
  source: string;
  source_page?: string | null;
  title?: string | null;
  author?: string | null;
  license?: string | null;
  attribution?: string | null;
  width?: number | null;
  height?: number | null;
  sort_order?: number;
  is_primary?: boolean;
};

export type Attraction = {
  id: number;
  name: string;
  description: string | null;
  category: string;
  primary_category?: string | null;
  secondary_categories?: string[];
  tags?: string[];
  latitude: string | number;
  longitude: string | number;
  estimated_visit_duration: number;
  rating: string | number | null;
  price_level: string | null;
  indoor_outdoor: string | null;
  opening_time: string | null;
  closing_time: string | null;
  created_at?: string;
  is_active?: boolean;
  is_featured?: boolean;
  data_quality_score?: number;
  popularity_score?: number;
  normalized_name?: string;
  cleaning_notes?: string;
  source?: string | null;
  source_id?: string | null;
  source_priority?: "osm_primary" | "manual_fallback" | "manual_only";
  canonical_key?: string;
  image_url?: string | null;
  thumbnail_url?: string | null;
  images?: AttractionImage[];
  description_source?: string | null;
  description_en?: string | null;
  description_en_source?: string | null;
};
