export type Attraction = {
  id: number;
  name: string;
  description: string | null;
  category: string;
  primary_category?: string | null;
  secondary_categories?: string[];
  tags?: string[];
  latitude: string | number;
  longitude: string | number;
  estimated_visit_duration: number;
  rating: string | number | null;
  price_level: string | null;
  indoor_outdoor: string | null;
  opening_time: string | null;
  closing_time: string | null;
  created_at?: string;
  is_active?: boolean;
  is_featured?: boolean;
  data_quality_score?: number;
  popularity_score?: number;
  normalized_name?: string;
  cleaning_notes?: string;
};
